### ISSUE TITLE
I have installed and granted full permissions but can't manage

### ISSUE THREAD

**Issue by pbthong** [rootuserdj/L3MON-Termux#1]
I built apk by below way:
https://user-images.githubusercontent.com/105858052/170813973-96acaf41-f34c-4ace-9b77-c461cec5e6fe.mp4

I then install the newly built apk and give it full permissions. But when I go to the management website, I still don't see my device:

https://user-images.githubusercontent.com/105858052/170814087-897d9f22-d857-457b-9c9d-5011d5dcdeca.mp4

Hope the admin will come up with a fix soon! Thanks

**Comment by rootuserdj** [comment]
Thank you for sharing your concern.
I'd request you to please watch the [full video,](https://t.me/efxtve/21087) to understand better .

Your feedback will be appreciated

**Comment by rootuserdj** [comment]
check in lan network first changing device last 2 device u have to try then after u can see the result
