### ISSUE TITLE
So excited... but one snafu..

### ISSUE THREAD

**Issue by Noideawhatdo** [rootuserdj/L3MON-Termux#2]
I've been trying to get this to work for me for moths (the older version) and  I am so excited I finally got through to the L3MON login page @localhost!! YAHOOO!!! I was so excited, but then.... i couldn't login.  I tried admin, with the password I made in lemon-termux, i tried rootuser, but nothing.  Can you please tell me what to do? I looked everywhere before reaching out. Thank you!

**Comment by Noideawhatdo** [comment]
I opened nano in maindb, changed password with hash but still can't login. I also tried to find the video to watch again, but it looks like it was taken down.  What am I doing incorrectly?

**Comment by rootuserdj** [comment]
lemon update and try again
